# Generated by Django 4.0.5 on 2022-06-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220630_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('admin', 'Accéder à la partie admin')]},
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'CREATOR'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
